### ISSUE TITLE
Semantic kernel

### ISSUE THREAD

**Issue by rploeg** [chriscrcodes/smart-factory#25]
You need to update your script for the front-end client:

_ERROR: No matching distribution found for semantic-kernel==1.10.0_

You need to use 1.14.0

**Comment by chriscrcodes** [comment]
Should be fixed with PR#26 and updated requirements.txt file with newer pip versions.
Can you please confirm?
Thank you!

**Comment by rploeg** [comment]
Yea confirmed!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
